language: java
jdk: oraclejdk8
sudo: false
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: karthicks/gremlin-ogm
      all_branches: true
      jdk: oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat gremlin-objects/target/surefire-reports/*.txt
cache:
  directories:
  - $HOME/.m2
